### ISSUE TITLE
Create component: wharf-cmd-provisioner

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#10]
> Inspired by [RFC-0025: wharf-cmd provisioning](https://iver-wharf.github.io/rfcs/published/0025-wharf-cmd-provisioning)

Subcommand: `wharf provisioner serve`

## Requirements

- Ability to create a new Kubernetes pod containing
	- labels:
		- `app=wharf-cmd-worker`
		- `app.kubernetes.io/name=wharf-cmd-worker`
		- `app.kubernetes.io/part-of=wharf`
		- `app.kubernetes.io/managed-by=wharf-cmd-provisioner`
		- `app.kubernetes.io/created-by=wharf-cmd-provisioner`
		- `wharf.iver.com/instance=prod` (value of the Wharf instance ID)
		- `wharf.iver.com/build-ref=123`
		- `wharf.iver.com/project-id=456`
	- init container that clones the Git repo for the pod via [`bitnami/git:2-debian-10`](https://hub.docker.com/layers/bitnami/git/2-debian-10/images/sha256-ebbe699c3c33a54bd9d430b331c97c70332eb143a7e85aa4b2643d57f64ee163?context=explore)
	- main container with image of `ubuntu:20.04` and command `ls -alh` to list the files in the cloned repo (just for testing to begin with)
	- emptyDir volume to mount the cloned Git repo into the main container

- Ability to list Kubernetes pods for pods with labels:
	- `app.kubernetes.io/name=wharf-cmd-worker`
	- `app.kubernetes.io/managed-by=wharf-cmd-provisioner`
	- `wharf.iver.com/instance=prod` (value of the Wharf instance ID)

- Ability to delete Kubernetes pods based on their ID, and error if they don't have the following labels:
	- `app.kubernetes.io/name=wharf-cmd-worker`
	- `app.kubernetes.io/managed-by=wharf-cmd-provisioner`
	- `wharf.iver.com/instance=prod` (value of the Wharf instance ID)

- REST API (see <https://iver-wharf.github.io/rfcs/published/0025-wharf-cmd-provisioning#wharf-cmd-provisioner-http-server>)

## Out of scope (don't focus on this yet)

- Feed build environment and other params to worker pod. Continued in #27

- Spin up actual wharf-cmd-worker pods. Instead stick with `ubuntu:20.04` testing images for now. Continued in #20 

- Making pod creation configurable (such as allowing additional env vars, labels, sidecars, etc). Continued in #24

- Add query parameters to `GET /api/worker` to find pods depending on their build or project ID. Continued in #21 

- Use in-cluster kubeconfigs. Instead rely on `~/.kube/config` for local testing. Continued in #19 

- Feed Git credentials automatically. Instead rely on a static k8s secret with SSH private key. Continued in #23

**Comment by Alexamakans** [comment]
I'll give this a go
