### ISSUE TITLE
Protobuf linting

### ISSUE THREAD

**Issue by applejag** [iver-wharf/wharf-cmd#16]
> Depends on:
> - #14

Found some alternatives:

1. <https://github.com/uber/prototool>: Includes linting and breaking change check. Need to investigate if this works with protobuf v3, and if so then it's the clear winner. Breaking change check is very valuable. No sign of GitHub Actions, but rolling our own shouldn't be that difficult.

2. <https://github.com/yoheimuta/protolint>: I (@jilleJr) have used this before and know it works well for protobuf v3. There's plenty of editor integrations available as well as GitHub Actions.

**Comment by jilleJr** [comment]
Requesting these to be added:

```Makefile
lint-proto:
	protolint lint api/workerapi
lint-fix-proto:
	protolint lint -fix api/workerapi
```

and adding them to `.PHONY` together with the other lint related things.

_Originally posted by @Alexamakans in https://github.com/iver-wharf/wharf-cmd/issues/128#issuecomment-1117247956_
