### ISSUE TITLE
Set k8s metadata on wharf-cmd-worker build pods

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#17]
> Inspired by [RFC-0025: wharf-cmd provisioning](https://iver-wharf.github.io/rfcs/published/0025-wharf-cmd-provisioning)

> Depends on:
> - #12

## Requirements

- When wharf-cmd-worker is creating the build pods, it should add:
	- ownerReference (if wharf-cmd-worker is also hosted in k8s), details: <https://iver-wharf.github.io/rfcs/published/0025-wharf-cmd-provisioning#wharf-cmd-worker-kubernetes-ownerreferences>
	- labels:
		- `app=wharf-cmd-worker-step`
		- `app.kubernetes.io/name=wharf-cmd-worker-step`
		- `app.kubernetes.io/part-of=wharf`
		- `app.kubernetes.io/managed-by=wharf-cmd-worker`
		- `app.kubernetes.io/created-by=wharf-cmd-worker`
		- `wharf.iver.com/instance=prod` (value of the Wharf instance ID)
		- `wharf.iver.com/build-ref=123`
		- `wharf.iver.com/project-id=456`
		- `wharf.iver.com/stage-id=789`
		- `wharf.iver.com/step-id=789`
	- annotations:
		- `wharf.iver.com/stage-name=myStage`
		- `wharf.iver.com/step-name=myStep`

## Out of scope (don't focus on this yet)

- Adding labels to Docker containers. This issue is only targeted towards k8s

**Comment by Alexamakans** [comment]
Currently there is code to set the annotations, but they are named `wharf.iver.com/stage` and `wharf.iver.com/step`.
Should those be kept as-is or changed?

**Comment by jilleJr** [comment]
> Currently there is code to set the annotations, but they are named `wharf.iver.com/stage` and `wharf.iver.com/step`. Should those be kept as-is or changed?
> 
> There is also the label `wharf.iver.com/build=true`, should this be kept in?

Good questions!

I'm commenting on this in your PR instead.

**Comment by jilleJr** [comment]
> Currently there is code to set the annotations, but they are named wharf.iver.com/stage and wharf.iver.com/step.
> Should those be kept as-is or changed?

But yes, I think they should be changed.
