### ISSUE TITLE
Collect build results from build pods in wharf-cmd-worker

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#28]
> Inspired by [RFC-0025: wharf-cmd provisioning](https://iver-wharf.github.io/rfcs/published/0025-wharf-cmd-provisioning)

> Depends on:
> - #12
> - #13

## Requirements

- Use Kubernetes API to do the equivalent of `kubectl logs ${podName} --timestamps --follow`

  - When reached EOF, check the status of the pod via equivalent API of `kubectl get pod ${podName}` to see if it's Completed or Failed.

- Use the `pkg/resultstore` from #13 to store the logs and build status updates.

## Out of scope (don't focus on this yet)

- Collect artifacts. The `.wharf-ci.yml` syntax doesn't support declaration of artifacts, so leave this to a future issue.

**Comment by jilleJr** [comment]
Use the interface from this file: https://github.com/iver-wharf/wharf-cmd/pull/43/files?diff=unified&w=0#diff-30a163f74f0d06e1cd8efd07b763fc3b39938268aa14ab7ab166a25a14ad48a0

**Comment by Alexamakans** [comment]
Taking over this issue from @Nisserino
