### ISSUE TITLE
Move root command to /cmd/wharf/wharf.go

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#35]
The binary is named `wharf-cmd`, which is clunky.

Want the binary to just be called `wharf`.

Go uses the directory name as the binary name, therefore we should move the main package to `/cmd/wharf/wharf.go`

## Alternatives

- Use `-o wharf` when building to force the binary name to be `wharf`. This is clunky though, and Windows users need to supply `-o wharf.exe` instead, so it'll be a weird mix. Better to just rely on Go's defaults.
	
	```sh
	# for Linux & Mac:
	go install -o wharf github.com/iver-wharf/wharf-cmd@latest
	# for Windows:
	go install -o wharf.exe github.com/iver-wharf/wharf-cmd@latest

	# vs...

	# for all:
	go install github.com/iver-wharf/wharf-cmd/cmd/wharf@latest
	```

- Rename the repository to `github.com/iver-wharf/wharf`. Thoughts?

**Comment by Alexamakans** [comment]
I prefer the first solution, moving to `/cmd/wharf/wharf.go`.

Hard no to using `-o wharf`/`-o wharf.exe`.

Would be okay with renaming the repository.

**Comment by fredx30** [comment]
Might be easier just to alias as needed? 4 letter exe names are more likely to collide than 8 letter ones. I cant imagine i personally would use the cli. That would also allow for aliasing to a 2 letter usage such as "wh" as needed if oen were to heavily use it for a while.

**Comment by fredx30** [comment]
Renaming the repo would also likely come with complications of broken links which i cant really see being fixed and cleaned up, it as would be hard to find all links.

**Comment by jilleJr** [comment]
> @fredx30 
> Might be easier just to alias as needed? 4 letter exe names are more likely to collide than 8 letter ones. I cant imagine i personally would use the cli. That would also allow for aliasing to a 2 letter usage such as "wh" as needed if oen were to heavily use it for a while.

The only collision is from other projects that are called Wharf. One candidate would be [itch.io's Wharf](https://github.com/itchio/wharf) protocol , but their CLI is named [`butler`](https://github.com/itchio/butler) so no collision there. Another would be [npm-wharf](https://github.com/npm-wharf), but they have no single CLI named Wharf either. These name collision with itch.io's Wharf and npm-wharf is a reason for a name change of Iver Wharf, but that's a separate issue. As of today, I can not find any other CLIs called Wharf.

Aliases are out of question as that's up to the user to define their own aliases. Aliases are also less conflicting as they are much easier to reassign.

> @fredx30 
> Renaming the repo would also likely come with complications of broken links which i cant really see being fixed and cleaned up, it as would be hard to find all links.

GitHub will supply redirects until that same name is taken again. So no links will get broken (including git remotes), just somewhat confusing (https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository).
