### ISSUE TITLE
Cancel build via SIGINT

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#81]
1. Listen for system signals: `syscall.SIGTERM`, `syscall.SIGHUP`, `os.Interrupt`, `os.Kill`
2. Cancel the root `context.Context`
3. After a grace period (e.g 10s), if cancelled context did not finish yet, force quit via `os.Exit`
4. If second interrupt signal is received, force quit via `os.Exit`.

Would be nice with a log message like:

```console
[INFO ] Cancelling build. Press ^C again to force quit.  gracePeriod=10s
[WARN ] Received second interrupt. Force quitting now.
```

or:

```console
[INFO ] Cancelling build. Press ^C again to force quit.  gracePeriod=10s
[WARN ] Failed to cancel within grace period. Force quitting now.
```

This cancelling logic should clean up by:

- Terminating any Kubernetes pods created by wharf-cmd-worker
- Close all file handles opened by resultstore
- Close all gRPC streaming connections

**Comment by Alexamakans** [comment]
Since file handles are closed automatically upon process termination for both Linux and Windows, is there a need for us to do this?

I am thinking calling `Freeze` would be enough. What do you think?

**Comment by jilleJr** [comment]
> Since file handles are closed automatically upon process termination for both Linux and Windows, is there a need for us to do this?
> 
> I am thinking calling `Freeze` would be enough. What do you think?

Won't be any unreleased file handles. Go's finalizers make sure of that, and probably the OS as well as you suggest.

However a close should be more severe than a freeze. In theory a `resultstore.Close()` should close all existing file handles and reject opening any new file handles.
